Remove code that licenses Burp Suite Pro
cisagov/ansible-role-burp-suite-pro pull request #59
Opened 2024-03-14 21:10 UTC by jsf9k

## 🗣 Description ##

This pull request removes the code that licenses Burp Suite Pro.

## 💭 Motivation and context ##

This all started because the license I was using expired.  I asked for an updated license. 
 According to a Tech Ops lab manager, the terms of the BSP license have changed.  We can no longer build pre-licensed AMIs since licenses are assigned per-user; therefore, the licensing code must be removed.

This creates a hardship for our users, but I checked with @m1j09830 and he said he is aware of this change and is expecting it.

## 🧪 Testing ##

All automated tests pass.

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] All relevant type-of-change labels have been added.
- [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [ ] All new and existing tests pass.

2024-03-15 08:09 UTC, mcdonnnj requested changes
If we have no plans to license Burp Suite Pro using this role please remove the `burp_suite_pro_license_object_name` variables from the `defaults/main.yml` file:
https://github.com/cisagov/ansible-role-burp-suite-pro/blob/7cc3f64b6021a69c9eb207a3f63fb20a57a7cd3c/defaults/main.yml#L9-L11
and the README:
https://github.com/cisagov/ansible-role-burp-suite-pro/blob/7cc3f64b6021a69c9eb207a3f63fb20a57a7cd3c/README.md?plain=1#L68
The `burp_suite_pro_users` variable from `defaults/main.yml`:
https://github.com/cisagov/ansible-role-burp-suite-pro/blob/7cc3f64b6021a69c9eb207a3f63fb20a57a7cd3c/defaults/main.yml#L34-L36
and the README:
https://github.com/cisagov/ansible-role-burp-suite-pro/blob/7cc3f64b6021a69c9eb207a3f63fb20a57a7cd3c/README.md?plain=1#L71
Please also update the Terraform configuration to update the S3 objects the testing role has permission to access:
https://github.com/cisagov/ansible-role-burp-suite-pro/blob/7cc3f64b6021a69c9eb207a3f63fb20a57a7cd3c/terraform/variables.tf#L19-L26
https://github.com/cisagov/ansible-role-burp-suite-pro/blob/7cc3f64b6021a69c9eb207a3f63fb20a57a7cd3c/terraform/variables.tf#L34-L41
as well as a pass on other variable language to remove references to a license. If it is no longer needed please remove the following dependency:
https://github.com/cisagov/ansible-role-burp-suite-pro/blob/7cc3f64b6021a69c9eb207a3f63fb20a57a7cd3c/defaults/main.yml#L15-L21

2024-03-15 15:34 UTC, dav3r approved these changes
👍  (with two tiny typos noted)

2024-03-15 15:34 UTC, dav3r commented on terraform/variables.tf
> +  description = "The name of the S3 bucket where the production Burp Suite Pro intaller lives."
Fix typo:
```suggestion
  description = "The name of the S3 bucket where the production Burp Suite Pro installer lives."
```

2024-03-15 15:34 UTC, dav3r commented on terraform/variables.tf
> +  description = "The name of the S3 bucket where the staging Burp Suite Pro intaller lives."
Fix typo:
```suggestion
  description = "The name of the S3 bucket where the staging Burp Suite Pro installer lives."
```

2024-03-19 19:47 UTC, mcdonnnj approved these changes
LGTM ✔

2024-03-19 19:48 UTC, merged